--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Debian 14.5-1.pgdg110+1)
-- Dumped by pg_dump version 14.5 (Debian 14.5-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" character varying(85) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO guest;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: guest
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetRoles" (
    "Id" character varying(85) NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(85),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO guest;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" character varying(85) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO guest;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: guest
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(85) NOT NULL,
    "ProviderKey" character varying(85) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" character varying(85) NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO guest;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" character varying(85) NOT NULL,
    "RoleId" character varying(85) NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO guest;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" character varying(85) NOT NULL,
    "LoginProvider" character varying(85) NOT NULL,
    "Name" character varying(85) NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO guest;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."AspNetUsers" (
    "Id" character varying(85) NOT NULL,
    "FirstName" text,
    "LastName" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" smallint NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" smallint NOT NULL,
    "TwoFactorEnabled" smallint NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" smallint NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO guest;

--
-- Name: IdentityUser; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."IdentityUser" (
    "Id" character varying(85) NOT NULL,
    "UserName" text,
    "NormalizedUserName" character varying(85),
    "Email" text,
    "NormalizedEmail" character varying(85),
    "EmailConfirmed" smallint NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" smallint NOT NULL,
    "TwoFactorEnabled" smallint NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" smallint NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."IdentityUser" OWNER TO guest;

--
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."RefreshTokens" (
    "Id" integer NOT NULL,
    "Token" text,
    "Expires" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    "RemoteIpAddress" text,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL
);


ALTER TABLE public."RefreshTokens" OWNER TO guest;

--
-- Name: RefreshTokens_Id_seq; Type: SEQUENCE; Schema: public; Owner: guest
--

ALTER TABLE public."RefreshTokens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RefreshTokens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FirstName" text,
    "LastName" text,
    "IdentityId" text,
    "UserName" text,
    "Address_Street" text,
    "Address_City" text,
    "Address_State" text,
    "Address_Country" text,
    "Address_ZipCode" text,
    "Created" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO guest;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: guest
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: guest
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO guest;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
1	8e12671b-6764-4828-8a7d-03fd3c4e6638	http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name	khteh
2	e1255b74-19c3-40e2-a2f1-96bf0a3562ca	http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name	mickey
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."AspNetUsers" ("Id", "FirstName", "LastName", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
8e12671b-6764-4828-8a7d-03fd3c4e6638	Kok How	Teh	khteh	KHTEH	khteh@email.com	KHTEH@EMAIL.COM	0	AQAAAAEAACcQAAAAEMH2UkfjTiDrr6o0C7BuwLPBM/brE0AZsjATXv0buFi19HPzLPRdxJmwMQXGgjBklQ==	PTZHYTK3GR6G3RGNECLB7MU3KLCDYLCF	0b75c0d1-3b28-456a-84b2-e1bde6171387	\N	0	0	\N	1	0
e1255b74-19c3-40e2-a2f1-96bf0a3562ca	Mickey	Mouse	mickey	MICKEY	mickey@email.com	MICKEY@EMAIL.COM	0	AQAAAAEAACcQAAAAENGpVbLNf0EDDrRa4HQs0BVsluU2g8v+D8uFPLSASFRz7fZFjejoPOptal607HskOQ==	BZVYV2UF3M5UGGEVRQLJZHP3DF6Q4PBF	bebf985e-4bb9-4a19-a639-db8d1f01217d	\N	0	0	\N	1	0
\.


--
-- Data for Name: IdentityUser; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."IdentityUser" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- Data for Name: RefreshTokens; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."RefreshTokens" ("Id", "Token", "Expires", "UserId", "RemoteIpAddress", "Created", "Modified") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."Users" ("Id", "FirstName", "LastName", "IdentityId", "UserName", "Address_Street", "Address_City", "Address_State", "Address_Country", "Address_ZipCode", "Created", "Modified") FROM stdin;
1	Kok How	Teh	8e12671b-6764-4828-8a7d-03fd3c4e6638	khteh	\N	\N	\N	\N	\N	2022-09-21 01:15:59.158735+00	2022-09-21 01:21:44.070471+00
2	Mickey	Mouse	e1255b74-19c3-40e2-a2f1-96bf0a3562ca	mickey	\N	\N	\N	\N	\N	2022-09-21 01:16:21.479951+00	2022-09-21 01:21:57.056212+00
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: guest
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20220919085849_Initial	6.0.9
20220919090617_Initial	6.0.9
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: guest
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: guest
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 2, true);


--
-- Name: RefreshTokens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: guest
--

SELECT pg_catalog.setval('public."RefreshTokens_Id_seq"', 4, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: guest
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 2, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: IdentityUser PK_IdentityUser; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."IdentityUser"
    ADD CONSTRAINT "PK_IdentityUser" PRIMARY KEY ("Id");


--
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_RefreshTokens_UserId; Type: INDEX; Schema: public; Owner: guest
--

CREATE INDEX "IX_RefreshTokens_UserId" ON public."RefreshTokens" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: guest
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: guest
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: RefreshTokens FK_RefreshTokens_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: guest
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

